# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NilsWaldowski.de
email: me@nilswaldowski.de
description: > # this means to ignore newlines until "baseurl:"
  Persönlicher Blog von Nils Waldowski über TYPO3, RWD (Responsive Webdesign), SASS, CSS, jQuery, HTML5, CMS, Workflow u.v.m.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.nilswaldowski.de" # the base hostname & protocol for your site
twitter_username: NilsWaldowski
github_username:  NilsWaldowski

# Build settings
markdown: kramdown
